export const GET_TEMPLATE_ID = "GET_TEMPLATE_ID";
export const GET_TEMPLATE_BY_NAME = "GET_TEMPLATE_BY_NAME";
export const GET_TEMPLATES = "GET_TEMPLATES";
export const GET_REVIEWS_TEMPLATE= 'GET_REVIEWS_TEMPLATE'
