export const GET_TEMPLATE_ID = "GET_TEMPLATE_ID";
export const GET_TEMPLATE_BY_SEARCH = "GET_TEMPLATE_BY_SEARCH";
export const GET_TEMPLATES = "GET_TEMPLATES";
export const ADD_FAV = "ADD_FAV";
export const REMOVE_FAV = "REMOVE_FAV";
