// Templates actions

export const GET_TEMPLATE_ID = "GET_TEMPLATE_ID";
export const SEARCH_NOT_FOUND = 'SEARCH_NOT_FOUND'
export const GET_TEMPLATE_BY_SEARCH = "GET_TEMPLATE_BY_SEARCH";
export const GET_TEMPLATES = "GET_TEMPLATES";
export const GET_FILTERED_TEMPLATES = "GET_FILTERED_TEMPLATES";
export const GET_TECHNOLOGIES = "GET_TECHNOLOGIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_FAV = "ADD_FAV";
export const REMOVE_FAV = "REMOVE_FAV";

//Reviews actions
export const GET_REVIEWS_USER= 'GET_REVIEWS_USER'
export const GET_REVIEWS_TEMPLATE= 'GET_REVIEWS_TEMPLATE'
export const POST_REVIEW= 'POST_REVIEW'
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';

// User actions

export const LOGIN = "LOGIN"
export const SIGNUP = "SIGNUP"
export const LOGOUT = "LOGOUT";
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

//  Cart actions

export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_TO_CART = "DELETE_TO_CART"
export const NOTFOUND_CART = "NOTFOUND_CART "
export const VIEW_CART = "VIEW_CART"